BandStore/Models/CartIndexViewModel.cs
using AbstraktApp.Domain.Entities;

namespace AbstraktApp.WebUI.Models
{
    public class CartIndexViewModel 
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

BandStore/Models/PagingInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbstraktApp.WebUI.Models
{
    public class PagingInfoViewModel
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }

        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

BandStore/Models/ProductsListViewModel.cs
using AbstraktApp.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AbstraktApp.WebUI.Models
{
    public class ProductsListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfoViewModel PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

BandStore/Controllers/AdminController.cs
using AbstraktApp.Domain.Abstract;
using AbstraktApp.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandStore.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController(IProductRepository repository)
        {
            this.repository = repository;
        }


        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ActionResult Edit(int productID)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductID == productID);

            return View(product);
        }
    }
}

BandStore/Controllers/CartController.cs
using AbstraktApp.Domain.Abstract;
using AbstraktApp.Domain.Entities;
using AbstraktApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

        public ActionResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }


        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Koszyk jest pusty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        // GET: Cart
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product!=null)
            {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }


        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnURL)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            if (product!=null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnURL });
        }


        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }


        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }
    }
}

BandStore/Controllers/HomeController.cs
using System.Web.Mvc;

namespace BandStore.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

BandStore/Controllers/NavController.cs
using AbstraktApp.Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BandStore.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;

        public NavController(IProductRepository repository)
        {
            this.repository = repository;
        }


        // GET: Nav
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct() // usuwa duplikaty
                .OrderBy(x => x);


            return PartialView(categories);
        }
    }
}

BandStore/Controllers/NewProductController.cs
using AbstraktApp.Domain.Abstract;
using AbstraktApp.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace AbstraktApp.WebUI.Controllers
{
    public class NewProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 6; // stronnicowanie(ilość wyświetlanych produktów)

        public NewProductController(IProductRepository productRepository)
        {
            repository = productRepository;            
        }

        // GET: NewProduct
        public ViewResult List(string category, int page = 1) // = 1 określa nam wartość default, nie musimy podawać parametru strony a i tak wyświetli pierwszy
        {
            ProductsListViewModel viewModel = new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfoViewModel
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? 
                    repository.Products.Count() :
                    repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(viewModel);
        }
    }
}

BandStore/Views/Admin/Edit.cshtml
@model AbstraktApp.Domain.Entities.Product

@{
    ViewBag.Title = "Administracja: edycja " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edycja @Model.Name</h2>

@using(Html.BeginForm())
{
    @Html.EditorForModel()
    <input type="submit" value="Zapisz" />
    @Html.ActionLink("Anuluj i wróć do listy ", "Index")
}

BandStore/Views/Admin/Index.cshtml
@model IEnumerable<AbstraktApp.Domain.Entities.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Wszystkie produkty</h1>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th class="NumericCol">Cena</th>
        <th>Ackje</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>@item.ProductID</td>
        <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
        <td class="NumericCol">@item.Price.ToString("c")</td>
        <td>
            @using (Html.BeginForm("Delete", "Admin"))
            {
                @Html.Hidden("ProductID", item.ProductID)
                <input type="submit" value="Usuń" />
            }
        </td>
    </tr>
    }

</table>

<p>@Html.ActionLink("Dodaj nowy produkt", "Create")</p>

BandStore/Views/Cart/Checkout.cshtml
@model AbstraktApp.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Abstrakt store: wysyłka";
}

<h2>Wysyłka</h2>
Proszę podać swoje dane, a towar zostanie natychmiast wysłany!

@using (Html.BeginForm())
{
    //wyświtla komunikaty o niepoprawnym wypełnieniu zamówienia/pustym koszyku
    @Html.ValidationSummary()

    <h3>Wysyłka dla:</h3>
    <div>Imie i nazwisko: @Html.EditorFor(x => x.Name)</div>

    <h3>Adres</h3>
    <div>Wiersz 1: @Html.EditorFor(x => x.Line1)</div>
    <div>Wiersz 2: @Html.EditorFor(x => x.Line2)</div>
    <div>Wiersz 3: @Html.EditorFor(x => x.Line3)</div>
    <div>Miasto: @Html.EditorFor(x => x.City)</div>
    <div>Kraj: @Html.EditorFor(x => x.Country)</div>
    <div>Województwo: @Html.EditorFor(x => x.State)</div>
    <div>Kod-pocztowy: @Html.EditorFor(x => x.Zip)</div>

    <h3>Opcje</h3>
    <label>
        @Html.EditorFor(x => x.GiftWrap)
        Pakowanie prezentu
    </label>

    <p align="center">
        <input class="actionButtons" type="submit" value="Zakończ zamówienie" />
    </p>
}

BandStore/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Abstrakt store - zamówienie zostało wysłane";
}

<h2>Dziękujemy</h2>
Dziękujemu za złożenie zamówienia. Wyślemy produkty ASAP!

BandStore/Views/Cart/Index.cshtml
@model AbstraktApp.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Abstrakt store: Twój koszyk";
}

<h2>Twój koszyk</h2>
<table width="90%" align="center">
    <thead>
        <tr>
            <th align="center">Ilość</th>
            <th align="left">Produkt</th>
            <th align="right">Cena</th>
            <th align="right">Wartość</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.Lines)
        {
        <tr>
            <td align="center">@item.Quantity</td>
            <td align="center">@item.Product.Name</td>
            <td align="left">@item.Product.Price.ToString()</td>
            <td align="right">@((item.Quantity * item.Product.Price).ToString("c"))</td>
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("ProductID", item.Product.ProductID)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="actionButtons" type="submit" value="Usuń" />
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Razem:</td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>

<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Kontynuuj zakupy</a>
    @Html.ActionLink("Wyślij zamówienie", "Checkout")
</p>

BandStore/Views/Cart/Summary.cshtml
@model AbstraktApp.Domain.Entities.Cart

<div id="cart">
    <span class="caption">
        <b>Twój koszyk</b>
        @Model.Lines.Sum(x => x.Quantity) sztuk.
        @Model.ComputeTotalValue().ToString("c")
    </span>

    @Html.ActionLink("Zamów", "Index", "Cart", new { returnUrl = Request.Url.PathAndQuery }, null)
</div>

BandStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BandStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<div class="col-md-6">
    <address>
        <strong>contact with band:</strong> <a href="mailto:puszynski@gmail.com">Jakub Puszynski</a>
    </address>
</div>


<div class="col-md-6">
    <h3>@ViewBag.Message</h3>
    <form method="post">
        <textarea name="message"></textarea>
        <input type="submit" value="Send" />
    </form>
</div>

BandStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="background-image: url('../../Content/band-baner.jpg'); background-repeat: no-repeat, repeat; background-size: 100%;">

    <h1 style="color:black;">Abstrakt music</h1>

    <p class="lead" style="color:black;">Check out the music. Abstrakt combines hypnotic melodies and power sound with impulsive compositions. Replacement role of guitar and bass, characteristic vocals and dynamic drums and synthesizer to create a unique sound. Immerse yourself – click on the icon below!</p>
    
    <p>
        <a href="https://abstraktband.bandcamp.com/releases" class="btn btn-primary btn-link" style="margin:20px;"><img src="https://i1.wp.com/abstraktband.com/wp-content/uploads/2015/01/bandcamp1.png?w=422" height="100" /></a>
        <a href="https://www.youtube.com/abstraktpl" class="btn btn-primary btn-link" style="margin: 20px;">
            <img src="~/Content/youtube.png" height="100" />
        </a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <iframe src="https://www.youtube.com/embed/AdgdE1kmZlw?feature=oembed" frameborder="0" allowfullscreen="" data-ratio="0.5621212121212121" data-width="660" data-height="371" style="display: block; margin: 0px; width: 100%;"></iframe>
        <h2>Concept album</h2>
        <p>
            Concept album Limbosis received high notes i.a. from 10/10 Guitarist Magazine, 9.5/10 Death Magnetic, 4,75/5 Power of Prog or 9,5/10 Death Magnetic. It also appears in various portals, magazines and foreign radio stations (ie. Prog Archives, DPRP, Prog Metal Zone – global, Prog Core – Canada, Prog Britannia – UK, Empire Magazine – Germany, Tzertzelos – Greece, Teraz Rock – Poland, Femforgacs – Hungary).
        </p>
    </div>
    <div class="col-md-4">
        <iframe src="https://www.youtube.com/embed/NPMTTMvm8mg?feature=oembed" frameborder="0" allowfullscreen="" data-ratio="0.5621212121212121" data-width="660" data-height="371" style="display: block; margin: 0px; width: 100%;"></iframe>
        <h2>Gloom</h2>
        <p>Imagine the world where the gloom, dread and heaviness clashes with the beauty of melodies and sounds. In the darkness, where the stage is illuminated by visualisations, Abstrakt will take you to the world you have never been to…</p>
    </div>
    <div class="col-md-4">
        <iframe src="https://www.youtube.com/embed/TLHwg46SOpw?feature=oembed" frameborder="0" allowfullscreen="" data-ratio="0.5621212121212121" data-width="660" data-height="371" style="display: block; margin: 0px; width: 100%;"></iframe>
        <h2>Lyric</h2>
        <p>Do you want to fill the shoes of the main character? Feel the plot and enjoy the ride? The best way to start up the trip with LIMBOSIS concept album is to listen to Teratoma lyric video:</p>
    </div>
</div>

BandStore/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@*Link do głównego kontrolera:*@
@Html.ActionLink("Wszystkie", "List", "NewProduct")

@foreach (var item in Model)
{
    @Html.RouteLink(item,
            new
            {
                controller = "NewProduct",
                action = "List",
                category = item,
                Page = 1
            },
        new
            {
                @class = item == ViewBag.SelectedCategory ? "selected" : null
            }
        )
}

BandStore/Views/NewProduct/List.cshtml
@model AbstraktApp.WebUI.Models.ProductsListViewModel

@{
    ViewBag.Title = "Produkty";
}


<div class="JPOwnAdd">
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
    </div>
    <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }  
    </div>
    <div id="content">


        @foreach (var item in Model.Products)
        {
            Html.RenderPartial("ProductSummary", item);
        }

        <div class="pager">
            @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
        </div>
    </div>
</div>

BandStore/Views/Shared/ProductSummary.cshtml
@model AbstraktApp.Domain.Entities.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description

    @using(Html.BeginForm("AddToCart", "Cart"))
    {
        @Html.HiddenFor(x => x.ProductID)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <input type="submit" value="+ Dodaj do koszyka" />
    }

    <h4>@Model.Price.ToString("c")</h4>
</div>

BandStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

BandStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Abstrakt", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Store", "", "")</li>                    
                    <li>@Html.ActionLink("More info", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ASP.NET Application created by Jakub Puszynski. All rights reserved </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>